using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;

namespace PollBall
{
    public class Startup
    {
        // Picking up where I left off on 06-09
        public void ConfigureServices(IServiceCollection services)
        {
        }
 
        public void Configure (IApplicationBuilder app)
        {
            // Moving UseStaticFiles ahead of Use added "?favorite=Basketball" to url

            app.Use(async (context, next) =>
            {
                if (context.Request.Query.ContainsKey("favorite"))
                {
                    string selectedValue = context.Request.Query["favorite"];
                    await context.Response.WriteAsync("Selected value is: " + selectedValue);
                }
                // Commenting out the else statement returned blank pages for home page and poll-questions page
                else
                {
                    await next.Invoke();
                }
            });

            app.UseStaticFiles();

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("This text was generated by the app. Run middleware.");
            });
        }
    }
}
